name: Gradle build action
description: 'Running gradle build and cache the results'
runs:
  using: "composite"
  steps:
#   - uses: actions/cache@v3
#     with:
#        path: |
#          ~/.gradle/caches
#          ~/.gradle/wrapper
#        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#        restore-keys: |
#          ${{ runner.os }}-gradle-

- name: Setup and execute Gradle 'build' task
  uses: gradle/gradle-build-action@v2
  with:
    arguments: build
