name: 'Gradle build action'
description: 'Running gradle build and cache the results'
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache
      with:
        path: .
        key: ${{ github.sha }}-a.txt

    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      
    - uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: build gradle
      if: steps.cache.outputs.cache-hit != 'true'
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
      
#    - name: list before build task
#      run: ls -1 **/subprojects
#      shell: bash
