name: 'Login to DockerHub'
description: 'Login to DockerHub by using the secrets, and use it in reusable-workflow'
inputs:
    - username:
        required: true
    - token:
        required: true
runs: 
  using: "composite"
  steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Login to Docker Hub
       uses: docker/login-action@v2.1.0
       with:
          username: ${{ inputs.username }}
          password: ${{ inputs.token }}
          
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
