name: Windows build

on: #[push, pull_request]
  workflow_dispatch:
jobs:
  build-win:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Caching
      uses: actions/cache@v1.2.1
      with:
        path: windows-build
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-state-${{github.sha}}
        restore-keys: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-state-${{github.sha}}
    - name: Install VC-Redist 2010 and 2012
      run: |
        Install-Module -Name VcRedist -Force
        $VcList = Get-VcList -Export All | Where-Object { $_.Release -eq "2010" -or $_.Release -eq "2012" }
        Save-VcRedist -VcList $VcList
        Install-VcRedist -VcList $VcList -Silent
    - name: Build with Gradle
      uses: ./.github/workflows/action
      
