name: CD docker publish
on: 
  workflow_call:
    secrets:
      username:
        required: true
      token:
        required: true
  workflow_dispatch:
  release:
    types: [published]
  
jobs:
  theta-cfa-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/docker-login
        with:
          token: ${{secrets.DOCKERHUB_TOKEN}}
          username: ${{secrets.DOCKER_USERNAME}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: blagazsolt/theta
          tags: type:raw, value=theta-cfa-cli

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/theta-cfa-cli.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  theta-sts-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/docker-login
        with:
          token: ${{secrets.DOCKERHUB_TOKEN}}
          username: ${{secrets.DOCKER_USERNAME}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: blagazsolt/theta
          tags: type:raw, value=theta-sts-cli

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/theta-sts-cli.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  theta-xsts-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/docker-login
        with:
          token: ${{secrets.DOCKERHUB_TOKEN}}
          username: ${{secrets.DOCKER_USERNAME}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: blagazsolt/theta
          tags: type:raw, value=theta-xsts-cli

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/ theta-xsts-cli.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  theta-xta-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/docker-login
        with:
          token: ${{secrets.DOCKERHUB_TOKEN}}
          username: ${{secrets.DOCKER_USERNAME}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: blagazsolt/theta
          tags: type:raw, value=theta-xta-cli

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/theta-xta-cli.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
