name: "Check formatting of .java files"

on:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check for formatting
      uses: leventeBajczi/intellij-idea-format@v0.1.1
      with:
        settings-file: "./doc/ThetaIntelliJCodeStyle.xml"
        file-mask: "*.java"
        additional-options: "-dry"
