name: Create release file
'on':
  workflow_dispatch: null
jobs:
  gradle:
    name: Run Gradle
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup and execute Gradle 'build' task
        uses: gradle/gradle-build-action@v2
        id: build
        with:
          arguments: build
      - run: 'echo "${{steps.build.outputs.build}}"'
      - uses: actions/upload-artifact@v3
        with:
          name: ProjlabWithGradle
          path: build/libs/*-all.jar
  publish:
    name: Publish Release
    needs: gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Creating version number
        run: >-
          echo "version=$(grep "version" build.gradle.kts | tail -n 1 | cut -d
          "=" -f2 | xargs echo )" >> $GITHUB_OUTPUT
        id: value
        shell: bash
      - run: 'echo "${{steps.value.outputs.version}}"'
      - uses: actions/download-artifact@v3
        with:
          name: ProjlabWithGradle
          path: jar/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: jar/
      - run: for i in jar/*; do mv $i $(echo $i | cut -d'-' -f1 | awk ' { print $1".jar" } '); done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: jar/*.jar
          body: "Auto-generated release"
          name: ${{steps.value.outputs.version}}
          tag_name: ${{steps.value.outputs.version}}
         
