name: Linux build

on: 
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - uses: gradle/gradle-build-action@v2
      with:
          arguments: --scan
    - uses: actions/upload-artifact@v3
      with:
          name: gradle-build
          path: subprojects/**
    
