name: Version Bump
on: 
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Specify the type of version bump'
        required: true
        type: chocie
        options:
            - major
            - minor
            - patch
        default: 'patch'
        

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Determine new version
      run: >-
        version=$(grep -Po '[0-9]+\.[0-9]+\.[0-9]+' build.gradle.kts)
        IFS='.' read -r -a array <<< "$version"
        echo "Previous version: $version"
        
      
    
